### ISSUE TITLE
[FEA] Support WKT?

### ISSUE THREAD

**Issue by voycey** [rapidsai/cuspatial#110]
All of our data is stored inside a data warehouse as text format WKT strings. This is very efficient for us as it means that we can directly process spatial data on both clusters and items like BigQuery, likewise it gives us agility in moving between different file formats (ORC, Parquet, CSV etc)

It would be great if we could directly read WKT strings into cuSpatial without having to convert to shapefiles as our data changes so often and the workflow to convert is cumbersome

**Comment by thomcom** [comment]
Yes! I'm investigating this possibility as one of my next features. Thanks!

**Comment by thomcom** [comment]
This wasn't followed up on when we released it, but currently you can use GeoPandas for WKT input, then convert that directly to cuspatial with `cuspatial.from_geopandas(geopandas_dataframe)`.

**Comment by harrism** [comment]
@voycey is this still of interest? If so, can you provide any information on how large the WKT datasets are?

**Comment by voycey** [comment]
Hi Mark,
Whilst I'm not actively working on Geospatial stuff right now I still don't think I would store things any differently  nowadays. WKT can be stored directly in PostGIS and BigQuery for example as WKT in a Geometry or Geography field type.
Not having to convert between formats would make CuSpatial a really nice options to work on our data.

Our WKT datasets were 200B point datasets X 140M polygons, upwards of 2TB of data each day

**Comment by isVoid** [comment]
With this scale of data, how often do you run into `GeometryCollection` data type in your collection? 
https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

**Comment by voycey** [comment]
Very rarely, the majority of our work was simple polygons and points, it was rare that we had multiple polygons for a single item, I think its possible that others would use them but I also think its equally possible that many dont!
